/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.0.M13
 * Generated at: 2017-02-27 13:52:52 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class ustatistics_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

private static org.apache.jasper.runtime.ProtectedFunctionMapper _jspx_fnmap_0;

static {
  _jspx_fnmap_0= org.apache.jasper.runtime.ProtectedFunctionMapper.getMapForFunction("fn:split", org.apache.taglibs.standard.functions.Functions.class, "split", new Class[] {java.lang.String.class, java.lang.String.class});
}

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/C:/Users/user/Desktop/hwhw/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/hw/WEB-INF/lib/standard-1.1.2.jar!/META-INF/c.tld", Long.valueOf(1098682290000L));
    _jspx_dependants.put("jar:file:/C:/Users/user/Desktop/hwhw/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/hw/WEB-INF/lib/standard-1.1.2.jar!/META-INF/fn.tld", Long.valueOf(1098682290000L));
    _jspx_dependants.put("/WEB-INF/jsp/unavigation.jsp", Long.valueOf(1488196321141L));
    _jspx_dependants.put("/WEB-INF/lib/standard-1.1.2.jar", Long.valueOf(1486176875158L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fif_0026_005ftest;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.release();
    _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    final java.lang.String _jspx_method = request.getMethod();
    if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
      return;
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=utf-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("     \r\n");
      out.write("     \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("<!--[if IE 7]><html class=\"ie7\" lang=\"zh\"><![endif]-->\r\n");
      out.write("<!--[if gt IE 7]><!-->\r\n");
      out.write("<html lang=\"zh\">\r\n");
      out.write("\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<!-- ???????????????????????? -->\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1\" />\r\n");
      out.write("\r\n");
      out.write("<!-- ? Bootstrap ?? CSS ?? -->\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!-- ???Bootstrap???????????? -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"http://cdn.bootcss.com/bootstrap/3.3.4/css/bootstrap-theme.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- jQuery??????bootstrap.min.js ???? -->\r\n");
      out.write("<script src=\"http://cdn.bootcss.com/jquery/1.11.2/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- ??? Bootstrap ?? JavaScript ?? -->\r\n");
      out.write("<script src=\"http://cdn.bootcss.com/bootstrap/3.3.4/js/bootstrap.min.js\"></script>\r\n");
      out.write("<title>大气的jQuery树型时间轴特效 - 站长素材</title>\r\n");
      out.write("<link href=\"./css/style.css\" rel=\"stylesheet\" type=\"text/css\" />\r\n");
      out.write("</head>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("     \r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\">\r\n");
      out.write("<!-- ???????????????????????? -->\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1, maximum-scale=1\" />\r\n");
      out.write("\r\n");
      out.write("<!-- ? Bootstrap ?? CSS ?? -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"http://cdn.bootcss.com/bootstrap/3.3.4/css/bootstrap.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- ???Bootstrap???????????? -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"http://cdn.bootcss.com/bootstrap/3.3.4/css/bootstrap-theme.min.css\">\r\n");
      out.write("\r\n");
      out.write("<!-- jQuery??????bootstrap.min.js ???? -->\r\n");
      out.write("<script src=\"http://cdn.bootcss.com/jquery/1.11.2/jquery.min.js\"></script>\r\n");
      out.write("\r\n");
      out.write("<!-- ??? Bootstrap ?? JavaScript ?? -->\r\n");
      out.write("<script src=\"http://cdn.bootcss.com/bootstrap/3.3.4/js/bootstrap.min.js\"></script>\r\n");
      out.write("\t<link rel=\"stylesheet\" href=\"http://cdn.static.runoob.com/libs/bootstrap/3.3.7/css/bootstrap.min.css\">\r\n");
      out.write("\t<script src=\"http://cdn.static.runoob.com/libs/jquery/2.1.1/jquery.min.js\"></script>\r\n");
      out.write("\t<script src=\"http://cdn.static.runoob.com/libs/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("<title>取消预订</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t<!-- 顶部导航栏 -->\r\n");
      out.write("    <nav class=\"navbar navbar-inverse navbar-fixed-top\" >\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"navbar-header\">\r\n");
      out.write("\r\n");
      out.write("            <a class=\"navbar-brand\" href=\"#\">Hostel World</a>\r\n");
      out.write("\r\n");
      out.write("            <!-- 分辨率低时显示的弹出顶部导航栏的按钮 <a class=\"navbar-brand\" href=\"#home\" data-toggle=\"tab\">Hostel World</a>-->\r\n");
      out.write("            <button type=\"button\" class=\"navbar-toggle collapsed\"\r\n");
      out.write("                data-toggle=\"collapse\" data-target=\"#navbar\" aria-expanded=\"false\"\r\n");
      out.write("                aria-controls=\"navbar\">\r\n");
      out.write("                <span class=\"sr-only\">Toggle navigation</span> <span\r\n");
      out.write("                    class=\"icon-bar\"></span> <span class=\"icon-bar\"></span> <span\r\n");
      out.write("                    class=\"icon-bar\"></span>\r\n");
      out.write("            </button>\r\n");
      out.write("\r\n");
      out.write("        </div>\r\n");
      out.write("        <div id=\"navbar\" class=\"navbar-collapse collapse\">\r\n");
      out.write("        \r\n");
      out.write("        \t<ul class=\"nav navbar-nav\">\r\n");
      out.write("        \t\t<li class=\"op\" id=\"order\"><a href=\"fuorder\">预定客栈</a></li>\r\n");
      out.write("        \t\t<li class=\"op\" id=\"orderCancel\"><a href=\"fuorderCancel\">取消预定</a></li>\r\n");
      out.write("                <li class=\"op\" id=\"statistics\"><a href=\"fustatistics\">统计信息</a></li>\r\n");
      out.write("        \t</ul>\r\n");
      out.write("        \t\r\n");
      out.write("            <ul class=\"nav navbar-nav navbar-right\"> \r\n");
      out.write("            \t<li><a href=\"index.jsp\"><span class=\"glyphicon glyphicon-log-out\"></span> 退出</a></li> \r\n");
      out.write("            </ul>\r\n");
      out.write("            <ul class=\"nav navbar-nav navbar-right\"> \r\n");
      out.write("            \t <li class=\"dropdown\" id=\"me\">\r\n");
      out.write("                \t<a href=\"#\" class=\"dropdown-toggle\"  data-toggle=\"dropdown\">\r\n");
      out.write("                \t");
      if (_jspx_meth_c_005fif_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                \t");
      if (_jspx_meth_c_005fif_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                   \t <b class=\"caret\"></b>\r\n");
      out.write("                \t</a>\r\n");
      out.write("                \t<ul class=\"dropdown-menu\">\r\n");
      out.write("                \t<li><a href=\"#\">修改密码</a></li>\r\n");
      out.write("                    \t");
      if (_jspx_meth_c_005fif_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                    \t");
      if (_jspx_meth_c_005fif_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("                    \t\r\n");
      out.write("                \t</ul>\r\n");
      out.write("           \t \t</li>\r\n");
      out.write("            </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("    </nav>\r\n");
      out.write("</body>\r\n");
      out.write("</html> ");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("$(\"#statistics\").addClass(\"active\");\r\n");
      out.write("</script>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("<div class=\"content\">\r\n");
      out.write("  <div class=\"wrapper\">\r\n");
      out.write("    <div class=\"light\"><i></i></div>\r\n");
      out.write("    <br/>\r\n");
      out.write("    <br/>\r\n");
      out.write("    <span class=\"line-left\"></span>\r\n");
      out.write("    <span class=\"line-right\"></span>\r\n");
      out.write("    <div class=\"main\">\r\n");
      out.write("      <h1 class=\"title\">Hostel World时间轴</h1>\r\n");
      out.write("      ");
      if (_jspx_meth_c_005fforEach_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("      <div class=\"year\">\r\n");
      out.write("        <h2><a href=\"#\">2014年<i></i></a></h2>\r\n");
      out.write("        <div class=\"list\">\r\n");
      out.write("          <ul>\r\n");
      out.write("            <li class=\"cls highlight\">\r\n");
      out.write("              <p class=\"date\">3月26日</p>\r\n");
      out.write("              <p class=\"intro\">微俱聚硬件微美图正式推出</p>\r\n");
      out.write("              <p class=\"version\">&nbsp;</p>\r\n");
      out.write("              <div class=\"more\">\r\n");
      out.write("                <p>首创微信集商务、娱乐一体化多媒体智能终端机微美图打印机</p>\r\n");
      out.write("                <p>营销推广活动支持导入SN码</p>\r\n");
      out.write("                <p>微商城模板，支持分类列表</p>\r\n");
      out.write("                <p>微商城完整支持微信支付</p>\r\n");
      out.write("                <p>微商城数据统计显示顺序更正</p>\r\n");
      out.write("                <p>微商城支持商品预览</p>\r\n");
      out.write("                <p>微商城订单成功后，网页将收到新订单通知</p>\r\n");
      out.write("                <p>幸运机活动时间延长至三个月等6个改进及Bug</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"cls\">\r\n");
      out.write("              <p class=\"date\">3月19日</p>\r\n");
      out.write("              <p class=\"intro\">全新会员卡3.0、微官网3.0、微商城2.0上线，渠道统计模块上线！</p>\r\n");
      out.write("              <p class=\"version\">&nbsp;</p>\r\n");
      out.write("              <div class=\"more\">\r\n");
      out.write("                <p>会员卡手机端会员卡页面全部改版，给用户更时尚大方的体验</p>\r\n");
      out.write("                <p>会员卡完全自定义会员用户信息</p>\r\n");
      out.write("                <p>会员卡支持领卡手机短信验证</p>\r\n");
      out.write("                <p>会员卡支持快捷充值，余额支付</p>\r\n");
      out.write("                <p>会员卡支持领取优惠券，代金券，礼品券</p>\r\n");
      out.write("                <p>会员卡支持开卡即送功能，包括开卡送优惠券，送积分，送代金券等等</p>\r\n");
      out.write("                <p>会员卡积分支持兑换礼品券</p>\r\n");
      out.write("                <p>会员卡支持给用户发送通知</p>\r\n");
      out.write("                <p>微商城中添加搜索框，增加商品的模糊匹配</p>\r\n");
      out.write("                <p>微商城中不同的商品详情，支持不同的配置</p>\r\n");
      out.write("                <p>微商城订单文档说明文字更详尽，并同时同步到订单说明里面</p>\r\n");
      out.write("                <p>微商城商品自动审核优化, 防止过滤过严</p>\r\n");
      out.write("                <p>微商城列表展现页的图片支持自适应大小</p>\r\n");
      out.write("                <p>微商城将图文与商品整合，提供统一的商品配置</p>\r\n");
      out.write("                <p>微官网提供多套底部导航菜单</p>\r\n");
      out.write("                <p>微官网的分类支持高级分类，高级分类同时也可以设置模板</p>\r\n");
      out.write("                <p>微官网支持背景动画</p>\r\n");
      out.write("                <p>微官网支持背景音乐</p>\r\n");
      out.write("                <p>渠道统计功能上线，用户可以通过生成二维码统计各渠道新增的粉丝</p>\r\n");
      out.write("                <p>美化门店的手机UI界面，并提供外链访问</p>\r\n");
      out.write("                <p>修复微活动的活动封面无法更换等5个Bug</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"cls\">\r\n");
      out.write("              <p class=\"date\">3月12日</p>\r\n");
      out.write("              <p class=\"intro\">首家支持微信支付，多客服系统上线！</p>\r\n");
      out.write("              <p class=\"version\">&nbsp;</p>\r\n");
      out.write("              <div class=\"more\">\r\n");
      out.write("                <p>为公众账号的微信支付提供技术接入，通过简单配置即可使用微信支付</p>\r\n");
      out.write("                <p>微信公众平台高级接口支持，通过认证的服务号可以使用多客服系统回复粉丝</p>\r\n");
      out.write("                <p>微商城首页添加多套模板，详情页支持模板自定义，商城购买商品支持微信支付；商城首页图片自适应等等十多个细节改进</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"cls\">\r\n");
      out.write("              <p class=\"date\">3月5日</p>\r\n");
      out.write("              <p class=\"intro\">360全景隆重上线！</p>\r\n");
      out.write("              <p class=\"version\">&nbsp;</p>\r\n");
      out.write("              <div class=\"more\">\r\n");
      out.write("                <p>全新360全景模块上线，3D看房、3D看车、3D看实景，一网打尽</p>\r\n");
      out.write("                <p>微官网新增24套一级模板</p>\r\n");
      out.write("                <p>微官网提供全局颜色调色器</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"cls\">\r\n");
      out.write("              <p class=\"date\">2月26日</p>\r\n");
      out.write("              <p class=\"intro\">微婚庆行业应用上线</p>\r\n");
      out.write("              <p class=\"version\">&nbsp;</p>\r\n");
      out.write("              <div class=\"more\">\r\n");
      out.write("                <p>提供更加友好的套餐价格</p>\r\n");
      out.write("                <p>提供经典案例，并可以二维码扫描</p>\r\n");
      out.write("                <p>提供更新日志，让您每周有惊喜</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"cls\">\r\n");
      out.write("              <p class=\"date\">2月19日</p>\r\n");
      out.write("              <p class=\"intro\">微信墙(微信大屏幕)上线</p>\r\n");
      out.write("              <p class=\"version\">&nbsp;</p>\r\n");
      out.write("              <div class=\"more\">\r\n");
      out.write("                <p>支持上墙、抽奖、投票等等功能的微信墙上线</p>\r\n");
      out.write("                <p>修正一战到底等多个模块的13个Bug, 并提供7个新改进</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"cls\">\r\n");
      out.write("              <p class=\"date\">2月12日</p>\r\n");
      out.write("              <p class=\"intro\">微贺卡上线</p>\r\n");
      out.write("              <p class=\"version\"></p>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"cls highlight\">\r\n");
      out.write("              <p class=\"date\">1月</p>\r\n");
      out.write("              <p class=\"intro\">微俱聚V6.0上线</p>\r\n");
      out.write("              <p class=\"version\">&nbsp;</p>\r\n");
      out.write("              <div class=\"more\">\r\n");
      out.write("                <p>确立每周迭代、周三发布，用户参与推动模块开发的小米模式</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"year\">\r\n");
      out.write("        <h2><a href=\"#\">2013年<i></i></a></h2>\r\n");
      out.write("        <div class=\"list\">\r\n");
      out.write("          <ul>\r\n");
      out.write("            <li class=\"cls\">\r\n");
      out.write("              <p class=\"date\">12月</p>\r\n");
      out.write("              <p class=\"intro\">微俱聚V5.4上线</p>\r\n");
      out.write("              <p class=\"version\">&nbsp;</p>\r\n");
      out.write("              <div class=\"more\">\r\n");
      out.write("                <p>形成完整的基础服务+互动推广+业务管理+行业应用+应用商店的服务架构</p>\r\n");
      out.write("                <p>注册用户突破10万，荣获“创业之星”大赛八强</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"cls\">\r\n");
      out.write("              <p class=\"date\">11月</p>\r\n");
      out.write("              <p class=\"intro\">微俱聚v5.3上线</p>\r\n");
      out.write("              <p class=\"version\">&nbsp;</p>\r\n");
      out.write("              <div class=\"more\">\r\n");
      out.write("                <p>全新渠道代理管理后台上线，更便捷更强大</p>\r\n");
      out.write("                <p>荣获2013年微应用最佳服务商</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"cls\">\r\n");
      out.write("              <p class=\"date\">10月</p>\r\n");
      out.write("              <p class=\"intro\">微俱聚V5.2上线</p>\r\n");
      out.write("              <p class=\"version\">&nbsp;</p>\r\n");
      out.write("              <div class=\"more\">\r\n");
      out.write("                <p>与众多行业建立合作，推出多个行业解决方案</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"cls\">\r\n");
      out.write("              <p class=\"date\">9月</p>\r\n");
      out.write("              <p class=\"intro\">微俱聚V5.1上线</p>\r\n");
      out.write("              <p class=\"version\">&nbsp;</p>\r\n");
      out.write("              <div class=\"more\">\r\n");
      out.write("                <p>发力行业O2O应用，为商家提供量身定制的行业方案</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"cls highlight\">\r\n");
      out.write("              <p class=\"date\">8月</p>\r\n");
      out.write("              <p class=\"intro\">全新微俱聚平台V5.0上线</p>\r\n");
      out.write("              <p class=\"version\">&nbsp;</p>\r\n");
      out.write("              <div class=\"more\">\r\n");
      out.write("                <p>推出微信应用商店，为商家提供更丰富的应用选择</p>\r\n");
      out.write("                <p>整合众多优秀微信应用，打造微应用分发平台</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"cls highlight\">\r\n");
      out.write("              <p class=\"date\">7月</p>\r\n");
      out.write("              <p class=\"intro\">微信加更名为微俱聚</p>\r\n");
      out.write("              <p class=\"version\">&nbsp;</p>\r\n");
      out.write("              <div class=\"more\">\r\n");
      out.write("                <p>出于品牌和商标保护的考虑，微信加平台更名</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"cls\">\r\n");
      out.write("              <p class=\"date\">6月</p>\r\n");
      out.write("              <p class=\"intro\">微信加V4.0上线</p>\r\n");
      out.write("              <p class=\"version\">&nbsp;</p>\r\n");
      out.write("              <div class=\"more\">\r\n");
      out.write("                <p>微信在线预约、更多微信互动模块和微官网模板，商家业务展现日渐丰富</p>\r\n");
      out.write("                <p>签约《中国好声音》，成为其微信独家战略合作伙伴</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"cls\">\r\n");
      out.write("              <p class=\"date\">5月</p>\r\n");
      out.write("              <p class=\"intro\">微信加V3.0上线</p>\r\n");
      out.write("              <p class=\"version\">&nbsp;</p>\r\n");
      out.write("              <div class=\"more\">\r\n");
      out.write("                <p>推出微信会员卡、微信团购等业务模块，打通更多商家业务</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"cls\">\r\n");
      out.write("              <p class=\"date\">4月</p>\r\n");
      out.write("              <p class=\"intro\">微信加V2.0上线</p>\r\n");
      out.write("              <p class=\"version\">&nbsp;</p>\r\n");
      out.write("              <div class=\"more\">\r\n");
      out.write("                <p>推出微官网等微信业务模块，实现微信与商家业务对接</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"cls\">\r\n");
      out.write("              <p class=\"date\">3月</p>\r\n");
      out.write("              <p class=\"intro\">微信加V1.0上线</p>\r\n");
      out.write("              <p class=\"version\">&nbsp;</p>\r\n");
      out.write("              <div class=\"more\">\r\n");
      out.write("                <p>微信基础服务模块+微信互动推广模块上线</p>\r\n");
      out.write("                <p>创造微信公众号一周涨5万粉的奇迹</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"cls\">\r\n");
      out.write("              <p class=\"date\">1月</p>\r\n");
      out.write("              <p class=\"intro\">全网第一个微信刮刮卡、大转盘上线</p>\r\n");
      out.write("              <p class=\"version\">&nbsp;</p>\r\n");
      out.write("              <div class=\"more\">\r\n");
      out.write("                <p>微信互动推广模块上线，用实际行动证明微信鸡汤有毒</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"year\">\r\n");
      out.write("        <h2><a href=\"#\">2012年<i></i></a></h2>\r\n");
      out.write("        <div class=\"list\">\r\n");
      out.write("          <ul>\r\n");
      out.write("            <li class=\"cls\">\r\n");
      out.write("              <p class=\"date\">8月</p>\r\n");
      out.write("              <p class=\"intro\">顿悟</p>\r\n");
      out.write("              <p class=\"version\">&nbsp;</p>\r\n");
      out.write("              <div class=\"more\">\r\n");
      out.write("                <p>顿悟，微信公众平台是企业移动互联网化的入口</p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </li>\r\n");
      out.write("            <li class=\"cls\">\r\n");
      out.write("              <p class=\"date\">8月以前</p>\r\n");
      out.write("              <p class=\"intro\">实现一个NB的社会化APP</p>\r\n");
      out.write("              <p class=\"version\">&nbsp;</p>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("      <div class=\"year\">\r\n");
      out.write("        <h2><a href=\"#\">2012年以前<i></i></a></h2>\r\n");
      out.write("        <div class=\"list\">\r\n");
      out.write("          <ul>\r\n");
      out.write("            <li class=\"cls\">\r\n");
      out.write("              <p class=\"date\">&nbsp;</p>\r\n");
      out.write("              <p class=\"intro\">适用浏览器：IE8、360、FireFox、Chrome、Safari、Opera、傲游、搜狗、世界之窗.</p>\r\n");
      out.write("              <p class=\"version\">&nbsp;</p>\r\n");
      out.write("              <div class=\"more\">\r\n");
      out.write("                <p></p>\r\n");
      out.write("              </div>\r\n");
      out.write("            </li>\r\n");
      out.write("          </ul>\r\n");
      out.write("        </div>\r\n");
      out.write("      </div>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"footer\">\r\n");
      out.write("  <div class=\"footer-content clearfix\">\r\n");
      out.write("    <div class=\"copyright\"> Copyright © 2011-2014  All Rights Reserved </div>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("<script type=\"text/javascript\" src=\"./js/jquery.min.js\"></script>\r\n");
      out.write("<script>\r\n");
      out.write("\t$(\".main .year .list\").each(function (e, target) {\r\n");
      out.write("\t    var $target=  $(target),\r\n");
      out.write("\t        $ul = $target.find(\"ul\");\r\n");
      out.write("\t    $target.height($ul.outerHeight()), $ul.css(\"position\", \"absolute\");\r\n");
      out.write("\t}); \r\n");
      out.write("\t$(\".main .year>h2>a\").click(function (e) {\r\n");
      out.write("\t    e.preventDefault();\r\n");
      out.write("\t    $(this).parents(\".year\").toggleClass(\"closeT\");\r\n");
      out.write("\t});\r\n");
      out.write("\t</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fif_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f0 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    try {
      _jspx_th_c_005fif_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f0.setParent(null);
      // /WEB-INF/jsp/unavigation.jsp(59,17) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f0.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userInfo.role==0 }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f0 = _jspx_th_c_005fif_005f0.doStartTag();
      if (_jspx_eval_c_005fif_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("个人信息");
          int evalDoAfterBody = _jspx_th_c_005fif_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f1 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    try {
      _jspx_th_c_005fif_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f1.setParent(null);
      // /WEB-INF/jsp/unavigation.jsp(60,17) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f1.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userInfo.role==1 }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f1 = _jspx_th_c_005fif_005f1.doStartTag();
      if (_jspx_eval_c_005fif_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("会员中心");
          int evalDoAfterBody = _jspx_th_c_005fif_005f1.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f1);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f2 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    try {
      _jspx_th_c_005fif_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f2.setParent(null);
      // /WEB-INF/jsp/unavigation.jsp(65,21) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f2.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userInfo.role==0 }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f2 = _jspx_th_c_005fif_005f2.doStartTag();
      if (_jspx_eval_c_005fif_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("<li><a href=\"fvipRegister\">注册会员</a></li>");
          int evalDoAfterBody = _jspx_th_c_005fif_005f2.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f2);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f3 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    try {
      _jspx_th_c_005fif_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f3.setParent(null);
      // /WEB-INF/jsp/unavigation.jsp(66,21) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f3.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${userInfo.role==1 }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f3 = _jspx_th_c_005fif_005f3.doStartTag();
      if (_jspx_eval_c_005fif_005f3 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("                    \t<li><a href=\"fvipRecharge\">会员充值</a></li>\r\n");
          out.write("                    \t<li><a href=\"fvipChange\">修改信息</a></li>\r\n");
          out.write("                        ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f3.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f3);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fforEach_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:forEach
    org.apache.taglibs.standard.tag.rt.core.ForEachTag _jspx_th_c_005fforEach_005f0 = (org.apache.taglibs.standard.tag.rt.core.ForEachTag) _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.get(org.apache.taglibs.standard.tag.rt.core.ForEachTag.class);
    try {
      _jspx_th_c_005fforEach_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fforEach_005f0.setParent(null);
      // /WEB-INF/jsp/ustatistics.jsp(46,6) name = items type = java.lang.Object reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setItems((java.lang.Object) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${orderTimeLine}", java.lang.Object.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      // /WEB-INF/jsp/ustatistics.jsp(46,6) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fforEach_005f0.setVar("o");
      int[] _jspx_push_body_count_c_005fforEach_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fforEach_005f0 = _jspx_th_c_005fforEach_005f0.doStartTag();
        if (_jspx_eval_c_005fforEach_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          do {
            out.write("\r\n");
            out.write("      \t");
            if (_jspx_meth_c_005fif_005f4(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("      \t\r\n");
            out.write("      \t\r\n");
            out.write("      \t\r\n");
            out.write("        ");
            if (_jspx_meth_c_005fif_005f7(_jspx_th_c_005fforEach_005f0, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
              return true;
            out.write("\r\n");
            out.write("      \t\r\n");
            out.write("      \t\r\n");
            out.write("      ");
            int evalDoAfterBody = _jspx_th_c_005fforEach_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
        }
        if (_jspx_th_c_005fforEach_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fforEach_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fforEach_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fforEach_005f0.doFinally();
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fforEach_0026_005fvar_005fitems.reuse(_jspx_th_c_005fforEach_005f0);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f4 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    try {
      _jspx_th_c_005fif_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/jsp/ustatistics.jsp(47,7) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f4.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.state==0 }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f4 = _jspx_th_c_005fif_005f4.doStartTag();
      if (_jspx_eval_c_005fif_005f4 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("      \t\t\r\n");
          out.write("      \t<div class=\"year\">\r\n");
          out.write("        <h2><a href=\"#\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:split(o.orderDate,\" \")[0]}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0));
          out.write("\r\n");
          out.write("        <i></i></a></h2>\r\n");
          out.write("        <div class=\"list\">\r\n");
          out.write("          <ul>\r\n");
          out.write("            <li class=\"cls\">\r\n");
          out.write("              <p class=\"date\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:split(o.orderDate,\" \")[1]}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0));
          out.write("</p>\r\n");
          out.write("              <p class=\"intro\">预定客栈</p>\r\n");
          out.write("              <p class=\"version\">&nbsp;</p>\r\n");
          out.write("              <div class=\"more\">\r\n");
          out.write("                <p>预定了位于");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.haddress }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('的');
          out.write('名');
          out.write('为');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.hname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('的');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.hlevel }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("客栈</p>\r\n");
          out.write("              </div>\r\n");
          out.write("            </li>\r\n");
          out.write("            ");
          if (_jspx_meth_c_005fif_005f5(_jspx_th_c_005fif_005f4, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\r\n");
          out.write("            \r\n");
          out.write("          </ul>\r\n");
          out.write("        </div>\r\n");
          out.write("      </div>\r\n");
          out.write("      \t\t");
          if (_jspx_meth_c_005fif_005f6(_jspx_th_c_005fif_005f4, _jspx_page_context, _jspx_push_body_count_c_005fforEach_005f0))
            return true;
          out.write("\r\n");
          out.write("      \r\n");
          out.write("      \t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f4.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f4);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f4, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f5 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    try {
      _jspx_th_c_005fif_005f5.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f4);
      // /WEB-INF/jsp/ustatistics.jsp(62,12) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f5.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:split(o.orderDate,' ')[0]  == fn:split(o.leaveDate,' ')[0] }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0)).booleanValue());
      int _jspx_eval_c_005fif_005f5 = _jspx_th_c_005fif_005f5.doStartTag();
      if (_jspx_eval_c_005fif_005f5 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("      \t\t\t<li class=\"cls\">\r\n");
          out.write("              \t<p class=\"date\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:split(o.leaveDate,\" \")[1]}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0));
          out.write("</p>\r\n");
          out.write("              \t<p class=\"intro\">取消预订</p>\r\n");
          out.write("              \t<p class=\"version\">&nbsp;</p>\r\n");
          out.write("              \t<div class=\"more\">\r\n");
          out.write("                \t<p>取消预定位于");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.haddress }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('的');
          out.write('名');
          out.write('为');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.hname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('的');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.hlevel }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("客栈</p>\r\n");
          out.write("              \t</div>\r\n");
          out.write("            \t</li>\r\n");
          out.write("            ");
          int evalDoAfterBody = _jspx_th_c_005fif_005f5.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f5);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f6(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fif_005f4, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f6 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    try {
      _jspx_th_c_005fif_005f6.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f6.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fif_005f4);
      // /WEB-INF/jsp/ustatistics.jsp(76,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f6.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:split(o.orderDate,' ')[0]  != fn:split(o.leaveDate,' ')[0] }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0)).booleanValue());
      int _jspx_eval_c_005fif_005f6 = _jspx_th_c_005fif_005f6.doStartTag();
      if (_jspx_eval_c_005fif_005f6 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("      \t\t\t<div class=\"year\">\r\n");
          out.write("        <h2><a href=\"#\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:split(o.leaveDate,' ')[0]}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0));
          out.write("<i></i></a></h2>\r\n");
          out.write("        <div class=\"list\">\r\n");
          out.write("          <ul>\r\n");
          out.write("           <li class=\"cls\">\r\n");
          out.write("              \t<p class=\"date\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:split(o.leaveDate,\" \")[1]}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0));
          out.write("</p>\r\n");
          out.write("              \t<p class=\"intro\">取消预订</p>\r\n");
          out.write("              \t<p class=\"version\">&nbsp;</p>\r\n");
          out.write("              \t<div class=\"more\">\r\n");
          out.write("                \t<p>取消预定位于");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.haddress }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('的');
          out.write('名');
          out.write('为');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.hname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('的');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.hlevel }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("客栈</p>\r\n");
          out.write("              \t</div>\r\n");
          out.write("            \t</li>\r\n");
          out.write("          \r\n");
          out.write("          </ul>\r\n");
          out.write("        </div>\r\n");
          out.write("      </div>\r\n");
          out.write("      \t\t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f6.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f6);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fif_005f7(javax.servlet.jsp.tagext.JspTag _jspx_th_c_005fforEach_005f0, javax.servlet.jsp.PageContext _jspx_page_context, int[] _jspx_push_body_count_c_005fforEach_005f0)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:if
    org.apache.taglibs.standard.tag.rt.core.IfTag _jspx_th_c_005fif_005f7 = (org.apache.taglibs.standard.tag.rt.core.IfTag) _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.get(org.apache.taglibs.standard.tag.rt.core.IfTag.class);
    try {
      _jspx_th_c_005fif_005f7.setPageContext(_jspx_page_context);
      _jspx_th_c_005fif_005f7.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_c_005fforEach_005f0);
      // /WEB-INF/jsp/ustatistics.jsp(99,8) name = test type = boolean reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fif_005f7.setTest(((java.lang.Boolean) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.state==1 }", boolean.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null)).booleanValue());
      int _jspx_eval_c_005fif_005f7 = _jspx_th_c_005fif_005f7.doStartTag();
      if (_jspx_eval_c_005fif_005f7 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        do {
          out.write("\r\n");
          out.write("        \r\n");
          out.write("      \t<div class=\"year\">\r\n");
          out.write("        <h2><a href=\"#\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:split(o.orderDate,\" \")[0]}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0));
          out.write("\r\n");
          out.write("        <i></i></a></h2>\r\n");
          out.write("        <div class=\"list\">\r\n");
          out.write("          <ul>\r\n");
          out.write("            <li class=\"cls\">\r\n");
          out.write("              <p class=\"date\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:split(o.orderDate,\" \")[1]}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0));
          out.write("</p>\r\n");
          out.write("              <p class=\"intro\">预定客栈</p>\r\n");
          out.write("              <p class=\"version\">&nbsp;</p>\r\n");
          out.write("              <div class=\"more\">\r\n");
          out.write("                <p>预定了位于");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.haddress }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('的');
          out.write('名');
          out.write('为');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.hname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('的');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.hlevel }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("客栈</p>\r\n");
          out.write("              </div>\r\n");
          out.write("            </li>\r\n");
          out.write("            <li class=\"cls\">\r\n");
          out.write("              <p class=\"date\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:split(o.orderDate,\" \")[1]}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0));
          out.write("</p>\r\n");
          out.write("              <p class=\"intro\">入住客栈</p>\r\n");
          out.write("              <p class=\"version\">&nbsp;</p>\r\n");
          out.write("              <div class=\"more\">\r\n");
          out.write("                <p>入住位于");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.haddress }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('的');
          out.write('名');
          out.write('为');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.hname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('的');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.hlevel }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("客栈</p>\r\n");
          out.write("              </div>\r\n");
          out.write("            </li>\r\n");
          out.write("            <li class=\"cls\">\r\n");
          out.write("              <p class=\"date\">");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${fn:split(o.orderDate,\" \")[1]}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, _jspx_fnmap_0));
          out.write("</p>\r\n");
          out.write("              <p class=\"intro\">离开客栈</p>\r\n");
          out.write("              <p class=\"version\">&nbsp;</p>\r\n");
          out.write("              <div class=\"more\">\r\n");
          out.write("                <p>离开位于");
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.haddress }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('的');
          out.write('名');
          out.write('为');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.hname}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write('的');
          out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${o.hlevel }", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
          out.write("客栈</p>\r\n");
          out.write("              </div>\r\n");
          out.write("            </li>\r\n");
          out.write("          </ul>\r\n");
          out.write("        </div>\r\n");
          out.write("      </div>\r\n");
          out.write("      \t");
          int evalDoAfterBody = _jspx_th_c_005fif_005f7.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
      }
      if (_jspx_th_c_005fif_005f7.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
    } finally {
      _005fjspx_005ftagPool_005fc_005fif_0026_005ftest.reuse(_jspx_th_c_005fif_005f7);
    }
    return false;
  }
}
